import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../layout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>IRB Autodrink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <p>Hola</p>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
