import type { NextPage } from "next";
import { motion, useTransform, useViewportScroll } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import Networks from "../components/Networks";
import Layout from "../layout";
import { useLayoutEffect, useRef, useState } from "react";

import { BsHeartFill, BsThreeDotsVertical, BsCartPlus } from "react-icons/bs";

const licors = [
  {
    name: "Daiquiri de maracuya",
    ingredients: [
      "30 ml - Zumo de limón",
      "30ml - Extracto de maracuya",
      "60ml - Ron blanco",
    ],
    image: "/images/daiquiri.webp",
  },
  {
    name: "Moscow mule",
    ingredients: [
      "30 ml - Zumo de limón",
      "30ml - Extracto de maracuya",
      "60ml - Ron blanco",
    ],
    image: "/images/moscow-mule.webp",
  },
];

const Licors: NextPage = () => {
  const { scrollY, scrollYProgress } = useViewportScroll();

  const opacity = useTransform(scrollY, [0, 500], [1, 0]);
  return (
    <div>
      <Head>
        <title>Catálogo - Autodrink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="w-full min-h-screen"></div>

        <div className="w-full min-h-screen relative">
          {licors.map((item, i) => (
            <div key={i} className="w-full">
              <motion.div className="w-full">
                <Image
                  className="image"
                  src={item.image}
                  alt={item.name}
                  layout="fill"
                />
              </motion.div>
              <motion.div className="absolute h-screen w-3/6 cover-image top-0 left-2/4 flex flex-col items-start justify-center backdrop-blur-sm">
                <div className="h-3/5 flex flex-col justify-center items-start px-10">
                  <span className="text-gray-500 text-lg">0{i + 1}</span>
                  <h1 className="text-white text-5xl font-normal">
                    {item.name}
                  </h1>
                </div>

                <div className="w-full flex h-2/5">
                  <div className="p-10 w-5/6 mr-16">
                    <h2 className="text-white text-md uppercase mb-4">
                      Ingredientes
                    </h2>

                    <div>
                      <ul>
                        {item.ingredients.map((item, i) => (
                          <li key={i} className="text-gray-500 text-sm mb-1">
                            {item}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                  <div className=" w-1/6 bg-stone-900">
                    <div className="w-full flex items-center justify-center h-1/3 text-white text-2xl hover:text-red-500">
                      <BsHeartFill />
                    </div>
                    <div className="w-full flex items-center justify-center h-1/3 text-white text-2xl">
                      <BsThreeDotsVertical />
                    </div>
                    <div className="w-full flex items-center justify-center h-1/3 text-white text-2xl">
                      <BsCartPlus />
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          ))}
        </div>
        <div className="w-full min-h-screen relative"></div>
      </Layout>
    </div>
  );
};

export default Licors;
