import Head from "next/head";
import Link from "next/link";
import React from "react";
import { BsArrowLeft } from "react-icons/bs";

const Registro = () => {
  return (
    <>
      <Head>
        <title>Registro - Autodrink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen flex items-center justify-center bg-white relative">
        <div className="absolute top-5 left-5">
          <Link href="/">
            <a className="flex items-center justify-center">
              <span className="h-8 w-8 flex items-center justify-center bg-black text-white rounded-full mr-1">
                <BsArrowLeft />
              </span>
              <span className="text-sm text-gray-400">Volver atras</span>
            </a>
          </Link>
        </div>
        <div className="w-2/5 h-4/6  flex flex-col items-center justify-start px-4 py-8">
          <h1 className="font-semibold text-3xl mb-1 uppercase">Registro</h1>
          <h2 className="text-sm mb-6">Crea tu cuenta nueva</h2>
          <div className="w-full my-2">
            <span className="text-sm text-gray-400 uppercase tracking-wider">
              Nombre
            </span>
            <input className="rounded-md w-full border-2 h-10 px-2" />
          </div>
          <div className="w-full my-2">
            <span className="text-sm text-gray-400 uppercase tracking-wider">
              Correo electrónico
            </span>
            <input className="rounded-md w-full border-2 h-10 px-2" />
          </div>
          <div className="w-full my-2">
            <span className="text-sm text-gray-400 uppercase tracking-wider">
              Contraseña
            </span>
            <input className="rounded-md w-full border-2 h-10 px-2" />
          </div>
          <div className="w-full my-2">
            <span className="text-sm text-gray-400 uppercase tracking-wider">
              Confirmar contraseña
            </span>
            <input className="rounded-md w-full border-2 h-10 px-2" />
          </div>
          <button className="px-2 py-2 border-2 mt-2 mb-4 rounded-lg text-gray-500 hover:text-red-400 hover:border-red-400 duration-200">
            Registrarse
          </button>
          <div>
            <span className="text-sm mr-2 text-gray-500">
              ¿Ya eres usuario?
            </span>
            <Link href="/ingreso">
              <a className="text-sm text-gray-500 hover:text-gray-700 hover:font-medium duration-200">
                Inicia sesión
              </a>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default Registro;
